In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("coaster_db.csv") # DF = DataFrame
df.head()

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,height_ft,Inversions_clean,Gforce_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,...,6 mph,9.7 km/h,6.0,mph,6.0,50.0,ft,NaN,0,2.9
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.0
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN

In [3]:
df.shape

(1087, 56)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1087 entries, 0 to 1086
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   coaster_name                   1087 non-null   str
 1   Length                         953 non-null    str
 2   Speed                          937 non-null    str
 3   Location                       1087 non-null   str
 4   Status                         874 non-null    str
 5   Opening date                   837 non-null    str
 6   Type                           1087 non-null   str
 7   Manufacturer                   1028 non-null   str
 8   Height restriction             831 non-null    str
 9   Model                          744 non-null    str
 10  Height                         965 non-null    str
 11  Inversions                     932 non-null    float64
 12  Lift/launch system             795 non-null    str
 13  Cost                           382 non-null    str
 14  Trains                         718 non-null    str
 15  Park section                   487 non-null    str
 16  Duration                       765 non-null    str
 17  Capacity                       575 non-null    str
 18  G-force                        362 non-null    str
 19  Designer                       578 non-null    str
 20  Max vertical angle             357 non-null    str
 21  Drop                           494 non-null    str
 22  Soft opening date              96 non-null     str
 23  Fast Lane available            69 non-null     str
 24  Replaced                       173 non-null    str
 25  Track layout                   335 non-null    str
 26  Fastrack available             19 non-null     str
 27  Soft opening date.1            96 non-null     str
 28  Closing date                   236 non-null    str
 29  Opened                         27 non-null     str
 30  Replaced by                    88 non-null     str
 31  Website                        87 non-null     str
 32  Flash Pass Available           50 non-null     str
 33  Must transfer from wheelchair  106 non-null    str
 34  Theme                          44 non-null     str
 35  Single rider line available    81 non-null     str
 36  Restraint Style                22 non-null     str
 37  Flash Pass available           46 non-null     str
 38  Acceleration                   60 non-null     str
 39  Restraints                     24 non-null     str
 40  Name                           35 non-null     str
 41  year_introduced                1087 non-null   int64
 42  latitude                       812 non-null    float64
 43  longitude                      812 non-null    float64
 44  Type_Main                      1087 non-null   str
 45  opening_date_clean             837 non-null    str
 46  speed1                         937 non-null    str
 47  speed2                         935 non-null    str
 48  speed1_value                   937 non-null    float64
 49  speed1_unit                    937 non-null    str
 50  speed_mph                      937 non-null    float64
 51  height_value                   965 non-null    float64
 52  height_unit                    965 non-null    str
 53  height_ft                      171 non-null    float64
 54  Inversions_clean               1087 non-null   int64
 55  Gforce_clean                   362 non-null    float64
dtypes: float64(8), int64(2), str(46)
memory usage: 475.7 KB

In [5]:
df.describe()

,Inversions,year_introduced,latitude,longitude,speed1_value,speed_mph,height_value,height_ft,Inversions_clean,Gforce_clean
count,932.000000,1087.000000,812.000000,812.000000,937.000000,937.000000,965.000000,171.000000,1087.000000,362.000000
mean,1.547210,1994.986201,38.373484,-41.595373,53.850374,48.617289,89.575171,101.996491,1.326587,3.824006
std,2.114073,23.475248,15.516596,72.285227,23.385518,16.678031,136.246444,67.329092,2.030854,0.989998
min,0.000000,1884.000000,-48.261700,-123.035700,5.000000,5.000000,4.000000,13.100000,0.000000,0.800000
25%,0.000000,1989.000000,35.031050,-84.552200,40.000000,37.300000,44.000000,51.800000,0.000000,3.400000
50%,0.000000,2000.000000,40.289800,-76.653600,50.000000,49.700000,79.000000,91.200000,0.000000,4.000000
75%,3.000000,2010.000000,44.799600,2.778100,63.000000,58.000000,113.000000,131.200000,2.000000,4.500000
max,14.000000,2022.000000,63.230900,153.426500,240.000000,149.100000,3937.000000,377.300000,14.000000,12.000000

In [6]:
df.isnull().sum()

coaster_name                        0
Length                            134
Speed                             150
Location                            0
Status                            213
Opening date                      250
Type                                0
Manufacturer                       59
Height restriction                256
Model                             343
Height                            122
Inversions                        155
Lift/launch system                292
Cost                              705
Trains                            369
Park section                      600
Duration                          322
Capacity                          512
G-force                           725
Designer                          509
Max vertical angle                730
Drop                              593
Soft opening date                 991
Fast Lane available              1018
Replaced                          914
Track layout                      752
Fastrack available               1068
Soft opening date.1               991
Closing date                      851
Opened                           1060
Replaced by                       999
Website                          1000
Flash Pass Available             1037
Must transfer from wheelchair     981
Theme                            1043
Single rider line available      1006
Restraint Style                  1065
Flash Pass available             1041
Acceleration                     1027
Restraints                       1063
Name                             1052
year_introduced                     0
latitude                          275
longitude                         275
Type_Main                           0
opening_date_clean                250
speed1                            150
speed2                            152
speed1_value                      150
speed1_unit                       150
speed_mph                         150
height_value                      122
height_unit                       122
height_ft                         916
Inversions_clean                    0
Gforce_clean                      725
dtype: int64

In [7]:
df = df.drop(columns=[
    'Fast Lane available',
    'Soft opening date',
    'Cost',
    'Replaced'
])

In [8]:
df.shape

(1087, 52)

In [9]:
df[['speed_mph', 'height_ft', 'Gforce_clean']].isnull().sum()

speed_mph       150
height_ft       916
Gforce_clean    725
dtype: int64

In [10]:
df = df.drop(columns=['height_ft', 'Gforce_clean'])
df.shape

(1087, 50)

In [11]:
df['speed_mph'].isnull().sum()

np.int64(150)

In [12]:
df['speed_mph'] = df['speed_mph'].fillna(df['speed_mph'].mean())

In [13]:
df['speed_mph'].isnull().sum()

np.int64(0)

In [14]:
df.iloc[0:5] # iloc = integer location

,coaster_name,Length,Speed,Location,Status,Opening date,Type,Manufacturer,Height restriction,Model,...,Type_Main,opening_date_clean,speed1,speed2,speed1_value,speed1_unit,speed_mph,height_value,height_unit,Inversions_clean
0,Switchback Railway,600 ft (180 m),6 mph (9.7 km/h),Coney Island,Removed,"June 16, 1884",Wood,LaMarcus Adna Thompson,NaN,Lift Packed,...,Wood,1884-06-16,6 mph,9.7 km/h,6.0,mph,6.000000,50.0,ft,0
1,Flip Flap Railway,NaN,NaN,Sea Lion Park,Removed,1895,Wood,Lina Beecher,NaN,NaN,...,Wood,1895-01-01,NaN,NaN,NaN,NaN,48.617289,NaN,NaN,1
2,Switchback Railway (Euclid Beach Park),NaN,NaN,"Cleveland, Ohio, United States",Closed,NaN,Other,NaN,NaN,NaN,...,Other,NaN,NaN,NaN,NaN,NaN,48.617289,NaN,NaN,0
3,Loop the Loop (Coney Island),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,Steel,1901-01-01,NaN,NaN,NaN,NaN,48.617289,NaN,NaN,1
4,Loop the Loop (Young's Pier),NaN,NaN,Other,Removed,1901,Steel,Edwin Prescott,NaN,NaN,...,Steel,1901-01-01,NaN,NaN,NaN,NaN,48.617289,NaN,NaN,1

In [15]:
df.iloc[0:5, 0:3]

                             coaster_name          Length             Speed
0                      Switchback Railway  600 ft (180 m)  6 mph (9.7 km/h)
1                       Flip Flap Railway             NaN               NaN
2  Switchback Railway (Euclid Beach Park)             NaN               NaN
3            Loop the Loop (Coney Island)             NaN               NaN
4            Loop the Loop (Young's Pier)             NaN               NaN

In [16]:
features = df[['speed_mph', 'Inversions_clean']]

In [17]:
features.head()

   speed_mph  Inversions_clean
0   6.000000                 0
1  48.617289                 1
2  48.617289                 0
3  48.617289                 1
4  48.617289                 1

In [19]:
tensor_data = tf.convert_to_tensor(features.values)
tensor_data.shape

TensorShape([1087, 2])

In [20]:
y = df['year_introduced']
y.head()

0    1884
1    1895
2    1896
3    1901
4    1901
Name: year_introduced, dtype: int64

In [21]:
y_tensor = tf.convert_to_tensor(y.values)
y_tensor.shape

TensorShape([1087])

In [22]:
reshaped_tensor = tf.reshape(tensor_data, (2, 1087))
reshaped_tensor.shape

TensorShape([2, 1087])

In [23]:
df['speed_per_inversion'] = df['speed_mph'] / (df['Inversions_clean'] + 1)
df[['speed_mph', 'Inversions_clean', 'speed_per_inversion']].head()

   speed_mph  Inversions_clean  speed_per_inversion
0   6.000000                 0             6.000000
1  48.617289                 1            24.308645
2  48.617289                 0            48.617289
3  48.617289                 1            24.308645
4  48.617289                 1            24.308645

In [24]:
new_feature_tensor = tf.convert_to_tensor(
    df['speed_per_inversion'].values
)
new_feature_tensor.shape

TensorShape([1087])